# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0004_auto_20170615_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
